Instance: bundle-provider-live-birth-babyg-quinn
InstanceOf: BundleDocumentBirthReport
Title: "Bundle - Provider Live Birth - Baby G Quinn"
Description: "Bundle - Provider Live Birth: Baby G Quinn example"
Usage: #example
* identifier.system = Canonical(CodeSystemIJEVitalRecords)
* identifier
  * value = "2019NJ15075"
  * extension[birthCertificateNumber].valueString = "15075"
  * extension[localFileNumber1].valueString = "444455555"
* timestamp = "2019-02-11T02:05:44.434Z"
* insert addentry(Composition, composition-provider-live-birth-babyg-quinn)
* insert addentry(Patient, patient-child-babyg-quinn)
* insert addentry(Encounter, encounter-birth-babyg-quinn)
* insert addentry(Encounter, encounter-maternity-jada-ann-quinn)
* insert addentry(Practitioner, practitioner-vital-records-avery-jones)
* insert addentry(Practitioner, practitioner-vital-records-janet-seito ) // why?
* insert addentry(Patient, patient-mother-jada-ann-quinn)
* insert addentry(Observation, observation-date-of-first-prenatal-care-visit-jada-ann-quinn)
* insert addentry(Observation, observation-number-prenatal-visits-jada-ann-quinn)
* insert addentry(Observation, observation-last-menstrual-period-jada-ann-quinn)
* insert addentry(Observation, observation-number-births-now-living-jada-ann-quinn)
* insert addentry(Observation, observation-number-births-now-dead-jada-ann-quinn)
* insert addentry(Observation, observation-date-of-last-live-birth-jada-ann-quinn)
* insert addentry(Observation, observation-number-other-pregnancy-outcomes-jada-ann-quinn)
* insert addentry(Observation, observation-date-of-last-other-pregnancy-outcome-jada-ann-quinn)
* insert addentry(Coverage, coverage-principal-payer-for-delivery-jada-ann-quinn)
* insert addentry(Observation, observation-mother-delivery-weight-jada-ann-quinn)
* insert addentry(Observation, observation-mother-height-jada-ann-quinn)
* insert addentry(Observation, observation-mother-prepregnancy-weight-jada-ann-quinn)
* insert addentry(Observation, observation-mother-received-wic-food-jada-ann-quinn)
* insert addentry(Observation, observation-cig-smoking-pregnancy-1-jada-ann-quinn)
* insert addentry(Observation, observation-cig-smoking-pregnancy-2-jada-ann-quinn)
* insert addentry(Observation, observation-cig-smoking-pregnancy-3-jada-ann-quinn)
* insert addentry(Observation, observation-cig-smoking-pregnancy-4-jada-ann-quinn)
* insert addentry(Condition, condition-prepregnancy-diabetes-jada-ann-quinn)
* insert addentry(Condition, condition-gestational-hypertension-jada-ann-quinn)
* insert addentry(Observation, observation-number-previous-cesareans-jada-ann-quinn)
* insert addentry(Condition, condition-infection-present-during-pregnancy-jada-ann-quinn)
* insert addentry(Procedure, procedure-obstetric-procedure-jada-ann-quinn)
* insert addentry(Condition, condition-chorioamnionitis-jada-ann-quinn)
* insert addentry(Procedure, procedure-induction-of-labor-jada-ann-quinn)
* insert addentry(Observation, observation-fetal-presentation-babyg-quinn)
* insert addentry(Procedure, procedure-final-route-method-delivery-babyg-quinn)
* insert addentry(Condition, condition-ruptured-uterus-jada-ann-quinn)
* insert addentry(Observation, observation-birth-weight-babyg-quinn)
* insert addentry(Observation, observation-gestational-age-at-delivery-babyg-quinn)
* insert addentry(Observation, observation-apgar-score-babyg-quinn-5-min)
* insert addentry(Observation, observation-apgar-score-babyg-quinn-10-min)
* insert addentry(Observation, observation-number-live-births-this-delivery-jada-ann-quinn)
* insert addentry(Condition, condition-congenital-anomaly-of-newborn-babyg-quinn)
* insert addentry(Condition, condition-congenital-anomaly-of-newborn-babyg-quinn-2)
* insert addentry(Observation, observation-infant-living-babyg-quinn)
* insert addentry(Observation, observation-infant-breastfed-at-discharge-babyg-quinn)
* insert addentry(Observation, observation-mother-married-during-pregnancy-jada-ann-quinn)
* insert addentry(Observation, observation-parent-education-level-jada-ann-quinn)
* insert addentry(Observation, observation-usual-work-jada-ann-quinn)
* insert addentry(Observation, observation-input-race-and-ethnicity-jada-ann-quinn)
* insert addentry(Observation, observation-ssn-requested-for-child-babyg-quinn)
* insert addentry(RelatedPerson, relatedperson-father-natural-james-brandon-quinn)
* insert addentry(Observation, observation-paternity-acknowledgement-signed-james-quinn)
* insert addentry(Observation, observation-parent-education-level-james-quinn)
* insert addentry(Observation, observation-usual-work-james-brandon-quinn)
* insert addentry(Observation, observation-input-race-and-ethnicity-james-quinn)
* insert addentry(QuestionnaireResponse, QuestionnaireResponse-mothers-live-birth-jada-quinn)
* insert addentry(Location, location-east-hospital)
* insert addentry(Location, location-south-hospital)
* insert addentry(Location, location-north-hospital)
* insert addentry(Organization, organization-south-hospital)
* insert addentry(Observation, observation-labor-trial-attempted-babyg-quinn)
//* insert addentry(RelatedPerson, relatedperson-mother-jada-ann-quinn)
* insert addentry(Procedure, procedure-infertility-treatment-jada-ann-quinn) 
* insert addentry(Procedure, procedure-artificial-insemination-jada-ann-quinn) 
* insert addentry(Observation, observation-antibiotics-during-labor-jada-ann-quinn) 
* insert addentry(Procedure, procedure-antibiotic-sepsis-babyg-quinn)
* insert addentry(Procedure,  procedure-epidural-or-spinal-anesthesia-jada-ann-quinn) 